INSERT INTO facebook_group VALUES (1, 'All of us', 'A group to bring us all togther', 1, CURRENT_TIMESTAMP);
INSERT INTO group_members VALUES (1,  1, TRUE);
INSERT INTO group_post VALUES (DEFAULT,  1, 1, 'hello everyone', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO group_members VALUES (1,  2, FALSE);
INSERT INTO group_members VALUES (1,  3, FALSE);
INSERT INTO group_members VALUES (1,  4, FALSE);
INSERT INTO group_members VALUES (1,  5, FALSE);
INSERT INTO group_members VALUES (1,  6, FALSE);
INSERT INTO group_members VALUES (1,  7, FALSE);
INSERT INTO group_members VALUES (1,  8, FALSE);
INSERT INTO group_members VALUES (1,  9, FALSE);
INSERT INTO group_members VALUES (1,  10, FALSE);
INSERT INTO group_members VALUES (1,  11, FALSE);
INSERT INTO group_members VALUES (1,  12, FALSE);
INSERT INTO group_members VALUES (1,  13, FALSE);
INSERT INTO group_members VALUES (1,  14, FALSE);
INSERT INTO group_members VALUES (1,  15, FALSE);
INSERT INTO group_members VALUES (1,  16, FALSE);
INSERT INTO group_members VALUES (1,  17, FALSE);
INSERT INTO group_members VALUES (1,  18, FALSE);
INSERT INTO group_members VALUES (1,  19, FALSE);
INSERT INTO group_members VALUES (1,  20, FALSE);
INSERT INTO facebook_group VALUES (2, 'Drama', 'Drama Queens 101', 2,  CURRENT_TIMESTAMP);
INSERT INTO group_members VALUES (2,  2, TRUE);
INSERT INTO group_members VALUES (2,  3, TRUE);
INSERT INTO group_members VALUES (2,  4, FALSE);
INSERT INTO group_members VALUES (2,  5, FALSE);
INSERT INTO group_members VALUES (2,  6, FALSE);
INSERT INTO group_members VALUES (2,  7, FALSE);
INSERT INTO group_members VALUES (2,  8, FALSE);
INSERT INTO group_members VALUES (2,  9, FALSE);
INSERT INTO group_members VALUES (2,  10, FALSE);
INSERT INTO group_members VALUES (2,  11, FALSE);
INSERT INTO group_members VALUES (2,  12, FALSE);
INSERT INTO group_post VALUES (DEFAULT,  2, 2, 'el ehtemam mabytelebsh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
